spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/control_practicantes
        username: postgres
        password: tu_password

    jpa:
        open-in-view: false

        hibernate:
            ddl-auto: validate

        properties:
            hibernate:
                default_schema: control_practicantes
                format_sql: true

    flyway:
        enabled: true
        default-schema: control_practicantes
        schemas:
            - control_practicantes
        locations: classpath:db/migration

logging:
    level:
        org.hibernate.SQL: debug

server:
  port: 8080

security:
    jwt:
        secret: "CAMBIAR_EN_PRODUCCION_SECRET_DE_256_BITS"
        expiration: 86400000
