spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/control_practicantes
    username: postgres
    password: 123456

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080

security:
    jwt:
        secret: "CAMBIAR_EN_PRODUCCION_SECRET_DE_256_BITS"
        expiration: 86400000
